name = "GreedyCraft2"
author = "mc_Edwin"
version = "2.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0aec26a18a17bbc32c9aaec5b6e346a1224b6852316562af027dc06ae75049f1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"
