#Configurations for material ManaQuartz.
[general]
	#The module blacklist of this material. "*" is an alias for all modules. If a module name occurs an odd number of times (including wildcards), then the module is blacklisted.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The color of this material.
	color = 10734557
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "crystal"
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
[molten]
	#The temperature of this molten fluid.
	temperature = 1000
[enderio]
	#The default byproduct material to output in Ender IO's sagmill.
	byproduct = "minecraft:cobblestone"
[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"
