[general]
	#The material blacklist of this module. "*" is an alias for all materials, and "*" followed with a material type name is an alias for all materials of that material type. If a material name occurs an odd number of times (including wildcards), then the material is blacklisted. These rules applies to all config material blacklists.
	materialBlacklist = []
[recipes]
	#The materials that should not have sagmill block to dust recipes added.
	blockToDustMaterialBlacklist = []
	#The materials that should not have sagmill material to dust recipes added.
	materialToDustMaterialBlacklist = []
